### ISSUE TITLE
App crashes with a null pointer exception with Preview 3 when an alarm triggers

### ISSUE THREAD

**Issue by pjcollins** [googlesamples/android-DirectBoot#4]
The app is crashing when an alarm fires, presumably because getting the alarm back from the intent extra is failing. I'm able to reproduce this consistently using a Nexus 5x running P3 (Build NPD35K).

Logcat output:

```
05-20 17:17:58.391   900  2840 E Parcel  : Class not found when unmarshalling: com.example.android.directboot.alarms.Alarm
05-20 17:17:58.391   900  2840 E Parcel  : java.lang.ClassNotFoundException: com.example.android.directboot.alarms.Alarm
05-20 17:17:58.391   900  2840 E Parcel  :  at java.lang.Class.classForName(Native Method)
05-20 17:17:58.391   900  2840 E Parcel  :  at java.lang.Class.forName(Class.java:400)
05-20 17:17:58.391   900  2840 E Parcel  :  at android.os.Parcel.readParcelableCreator(Parcel.java:2490)
05-20 17:17:58.391   900  2840 E Parcel  :  at android.os.Parcel.readParcelable(Parcel.java:2444)
05-20 17:17:58.391   900  2840 E Parcel  :  at android.os.Parcel.readValue(Parcel.java:2347)
05-20 17:17:58.391   900  2840 E Parcel  :  at android.os.Parcel.readArrayMapInternal(Parcel.java:2700)
05-20 17:17:58.391   900  2840 E Parcel  :  at android.os.BaseBundle.unparcel(BaseBundle.java:269)
05-20 17:17:58.391   900  2840 E Parcel  :  at android.os.Bundle.putAll(Bundle.java:226)
05-20 17:17:58.391   900  2840 E Parcel  :  at android.content.Intent.fillIn(Intent.java:8175)
05-20 17:17:58.391   900  2840 E Parcel  :  at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:235)
05-20 17:17:58.391   900  2840 E Parcel  :  at com.android.server.am.PendingIntentRecord.send(PendingIntentRecord.java:203)
05-20 17:17:58.391   900  2840 E Parcel  :  at android.app.PendingIntent.send(PendingIntent.java:806)
05-20 17:17:58.391   900  2840 E Parcel  :  at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:2972)
05-20 17:17:58.391   900  2840 E Parcel  :  at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2418)
05-20 17:17:58.391   900  2840 E Parcel  :  at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2536)
05-20 17:17:58.391   900  2840 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.example.android.directboot.alarms.Alarm
05-20 17:17:58.391   900  2840 E Parcel  :  at java.lang.Class.classForName(Native Method)
05-20 17:17:58.391   900  2840 E Parcel  :  at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
05-20 17:17:58.391   900  2840 E Parcel  :  at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
05-20 17:17:58.391   900  2840 E Parcel  :  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-20 17:17:58.391   900  2840 E Parcel  :  ... 15 more
05-20 17:17:58.391   900  2840 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-20 17:17:58.393   900  2840 W Bundle  : Failed to parse Bundle, but defusing quietly
05-20 17:17:58.393   900  2840 W Bundle  : android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.example.android.directboot.alarms.Alarm
05-20 17:17:58.393   900  2840 W Bundle  :  at android.os.Parcel.readParcelableCreator(Parcel.java:2518)
05-20 17:17:58.393   900  2840 W Bundle  :  at android.os.Parcel.readParcelable(Parcel.java:2444)
05-20 17:17:58.393   900  2840 W Bundle  :  at android.os.Parcel.readValue(Parcel.java:2347)
05-20 17:17:58.393   900  2840 W Bundle  :  at android.os.Parcel.readArrayMapInternal(Parcel.java:2700)
05-20 17:17:58.393   900  2840 W Bundle  :  at android.os.BaseBundle.unparcel(BaseBundle.java:269)
05-20 17:17:58.393   900  2840 W Bundle  :  at android.os.Bundle.putAll(Bundle.java:226)
05-20 17:17:58.393   900  2840 W Bundle  :  at android.content.Intent.fillIn(Intent.java:8175)
05-20 17:17:58.393   900  2840 W Bundle  :  at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:235)
05-20 17:17:58.393   900  2840 W Bundle  :  at com.android.server.am.PendingIntentRecord.send(PendingIntentRecord.java:203)
05-20 17:17:58.393   900  2840 W Bundle  :  at android.app.PendingIntent.send(PendingIntent.java:806)
05-20 17:17:58.393   900  2840 W Bundle  :  at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:2972)
05-20 17:17:58.393   900  2840 W Bundle  :  at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2418)
05-20 17:17:58.393   900  2840 W Bundle  :  at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2536)
--------- beginning of system
05-20 17:17:58.413   900   900 D ConditionProviders.SCP: onReceive android.app.action.NEXT_ALARM_CLOCK_CHANGED
05-20 17:17:58.413   900   900 D ConditionProviders.SCP: notifyCondition condition://android/schedule?days=6.7&start=23.30&end=10.0&exitAtAlarm=false STATE_FALSE reason=!meetsSchedule
05-20 17:17:58.413   900   900 D ConditionProviders.SCP: notifyCondition condition://android/schedule?days=1.2.3.4.5&start=22.0&end=7.0&exitAtAlarm=false STATE_FALSE reason=!meetsSchedule
05-20 17:17:58.414   900   900 D ConditionProviders.SCP: Scheduling evaluate for Fri May 20 22:00:00 EDT 2016 (1463796000000), in +4h42m1s587ms, now=Fri May 20 17:17:58 EDT 2016 (1463779078413)
--------- beginning of crash
05-20 17:17:58.416  7642  7750 E AndroidRuntime: FATAL EXCEPTION: IntentService[com.example.android.directboot.alarms.AlarmIntentService]
05-20 17:17:58.416  7642  7750 E AndroidRuntime: Process: com.example.android.directboot, PID: 7642
05-20 17:17:58.416  7642  7750 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int com.example.android.directboot.alarms.Alarm.hour' on a null object reference
05-20 17:17:58.416  7642  7750 E AndroidRuntime:    at com.example.android.directboot.alarms.AlarmIntentService.onHandleIntent(AlarmIntentService.java:54)
05-20 17:17:58.416  7642  7750 E AndroidRuntime:    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
05-20 17:17:58.416  7642  7750 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
05-20 17:17:58.416  7642  7750 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
05-20 17:17:58.416  7642  7750 E AndroidRuntime:    at android.os.HandlerThread.run(HandlerThread.java:61)
05-20 17:17:58.420   900   911 W ActivityManager:   Force finishing activity com.example.android.directboot/.MainActivity
```

**Comment by thagikura** [comment]
Thanks for the report.

Should be fixed by #5. (It's a workaround though, at least it avoids NPE)
